baseurl = "https://dankleiman.com/"
languageCode = "en-us"
title = "Dan Kleiman"
theme = "PaperMod"
paginate = 10

googleAnalytics = "UA-19970008-2"

[markup.goldmark.renderer]
  unsafe = true

[params]
  description = "Tai Chi, Code, and Whatever from Dan Kleiman"
  author = "Dan Kleiman"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = false
  disableThemeToggle = true

[params.homeInfoParams]
  Title = "Dan Kleiman"
  Content = "Writing about tai chi and code."

[permalinks]
  taichi = "/taichi/:contentbasename"
  code = "/code/:contentbasename"

[[menu.main]]
  name = "Tai Chi"
  url = "/taichi/"
  identifier = "taichi"
  weight = 1

[[menu.main]]
  name = "Code"
  url = "/code/"
  identifier = "code"
  weight = 2

[[menu.main]]
  name = "About"
  url = "/about/"
  identifier = "about"
  weight = 3

[social]
  github  = "dankleiman"
  twitter = "Dan_Kleiman"
  email   = "info@dankleiman.com"
